FROM python:3.6

# use pip caching (COPYs and ADDs in this order!)
COPY requirements.txt /
WORKDIR /
RUN pip install -r requirements.txt
# add required models after the package installation
RUN python -m spacy download en
RUN python -m spacy download de

# now add the rest
ENV TZ=Europe/Berlin

COPY app.py /
COPY analysis.py /

CMD ["python", "app.py"]
